### PR TITLE
Support uninstall/upgrade

### PR DESCRIPTION
**Pull request by astoltz**
* Stop services before upgrading/uninstalling.
* Install to main tools\ directory rather than changing folder path.
* Mark packetbeat as needing winpcap.

### CODE REVIEW

**Comment by rukas** [comment]
@palethorper can this get reviewed?  I'm unable to upgrade any of the beats via chocolatey and this appears to be the issue.

**Comment by palethorper** [comment]
Apologies - have been busy at work.
I will review in the next couple of days.
I think that the change in the install that moves file up folder will leave residual files around on uninstall.

Also - moving the files to up a folder is a breaking change for people who install with choco but use another tool to configure (chef, ansible etc.) 

Will review properly though

**Comment by astoltz** [comment]
Use with chef is particularly why I want the configuration file directly in tools. No matter what version is deployed, the files are always in the same spot.

The documentation for https://chocolatey.org/docs/helpers-uninstall-chocolatey-zip-package says " This is not necessary if the files are unzipped to the package directory."

My tests have shown the folder gets properly cleaned up on uninstall as well.

**Comment by palethorper** [comment]
Have merge this in now.
Note - the install path has now changed to the lib\[beatname]\tools\[beatname] folder directly (no longer as version dependent sub-folder)
https://github.com/palethorper/chocolatey-packages/commit/df73a60c3419ab65d2ad273cbe4dd1913331a1c2

**Comment by palethorper** [comment]
Note - next release of beats package will contain changes

**Pull request closed without merging**
